/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { OwnableContract } from "./Ownable";
import { IERC1155ErrorsContract } from "./IERC1155Errors";
import { IERC20ErrorsContract } from "./IERC20Errors";
import { IERC721ErrorsContract } from "./IERC721Errors";
import { ERC20Contract } from "./ERC20";
import { IERC20MetadataContract } from "./IERC20Metadata";
import { IERC20Contract } from "./IERC20";
import { FtsoV2FeedConsumerContract } from "./FtsoV2FeedConsumer";
import { FtsoV2InterfaceContract } from "./FtsoV2Interface";
import { GAEHEscrowContract } from "./GAEHEscrow";
import { IInsuranceOracleContract } from "./IInsuranceOracle";
import { MockInsuranceOracleContract } from "./MockInsuranceOracle";
import { MockStablecoinContract } from "./MockStablecoin";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "Ownable"): OwnableContract;
      require(name: "IERC1155Errors"): IERC1155ErrorsContract;
      require(name: "IERC20Errors"): IERC20ErrorsContract;
      require(name: "IERC721Errors"): IERC721ErrorsContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "IERC20Metadata"): IERC20MetadataContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "FtsoV2FeedConsumer"): FtsoV2FeedConsumerContract;
      require(name: "FtsoV2Interface"): FtsoV2InterfaceContract;
      require(name: "GAEHEscrow"): GAEHEscrowContract;
      require(name: "IInsuranceOracle"): IInsuranceOracleContract;
      require(name: "MockInsuranceOracle"): MockInsuranceOracleContract;
      require(name: "MockStablecoin"): MockStablecoinContract;
    }
  }
}

export { OwnableContract, OwnableInstance } from "./Ownable";
export {
  IERC1155ErrorsContract,
  IERC1155ErrorsInstance,
} from "./IERC1155Errors";
export { IERC20ErrorsContract, IERC20ErrorsInstance } from "./IERC20Errors";
export { IERC721ErrorsContract, IERC721ErrorsInstance } from "./IERC721Errors";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export {
  IERC20MetadataContract,
  IERC20MetadataInstance,
} from "./IERC20Metadata";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  FtsoV2FeedConsumerContract,
  FtsoV2FeedConsumerInstance,
} from "./FtsoV2FeedConsumer";
export {
  FtsoV2InterfaceContract,
  FtsoV2InterfaceInstance,
} from "./FtsoV2Interface";
export { GAEHEscrowContract, GAEHEscrowInstance } from "./GAEHEscrow";
export {
  IInsuranceOracleContract,
  IInsuranceOracleInstance,
} from "./IInsuranceOracle";
export {
  MockInsuranceOracleContract,
  MockInsuranceOracleInstance,
} from "./MockInsuranceOracle";
export {
  MockStablecoinContract,
  MockStablecoinInstance,
} from "./MockStablecoin";
