/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface FtsoV2FeedConsumerContract
  extends Truffle.Contract<FtsoV2FeedConsumerInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<FtsoV2FeedConsumerInstance>;
}

type AllEvents = never;

export interface FtsoV2FeedConsumerInstance extends Truffle.ContractInstance {
  flrUsdId(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getAvailablePriceFeedNames(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  getAvailablePriceFeeds(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string[]>;

  getCurrentPrice(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: BN }>;

  getFeedPrice(
    feedId: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: BN }>;

  getFeedPriceByName(
    feedName: string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: BN }>;

  getFlrUsdPrice(
    txDetails?: Truffle.TransactionDetails
  ): Promise<{ 0: BN; 1: BN; 2: BN }>;

  methods: {
    flrUsdId(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getAvailablePriceFeedNames(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    getAvailablePriceFeeds(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string[]>;

    getCurrentPrice(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN }>;

    getFeedPrice(
      feedId: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN }>;

    getFeedPriceByName(
      feedName: string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN }>;

    getFlrUsdPrice(
      txDetails?: Truffle.TransactionDetails
    ): Promise<{ 0: BN; 1: BN; 2: BN }>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
